apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peer-host
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - exportPodCIDR: true
      localASN: 65013
      neighbors:
        - peerASN: 65012
          peerAddress: 172.28.0.1/32
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
      serviceSelector:
          # announce ALL LoadBalancer services within the cluster
          matchExpressions:
            - {key: somekey, operator: NotIn, values: ['never-used-value']}
  